/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
export {}
declare global {
  const IconDoraAptos: typeof import('~icons/dora/aptos.jsx')['default']
  const IconDoraInjective: typeof import('~icons/dora/injective.jsx')['default']
  const IconDoraLogo: typeof import('~icons/dora/logo.jsx')['default']
  const IconFluentLive24Filled: typeof import('~icons/fluent/live24-filled.jsx')['default']
  const IconMdiBuild: typeof import('~icons/mdi/build.jsx')['default']
  const IconMdiChevronDown: typeof import('~icons/mdi/chevron-down.jsx')['default']
  const IconMdiChevronRight: typeof import('~icons/mdi/chevron-right.jsx')['default']
  const IconMdiCode: typeof import('~icons/mdi/code.jsx')['default']
  const IconMdiLightBulbOn: typeof import('~icons/mdi-light/bulb-on.jsx')['default']
  const IconMdiLightbulbOn: typeof import('~icons/mdi/lightbulb-on.jsx')['default']
  const IconMdiLoginVariant: typeof import('~icons/mdi/login-variant.jsx')['default']
  const IconMdiMoney: typeof import('~icons/mdi/money.jsx')['default']
  const IconMdiSkull: typeof import('~icons/mdi/skull.jsx')['default']
}
